services:
  - type: web
    name: medical-chat-bot-ai-fronted
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.19.0
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_SUPABASE_PROJECT_ID
        sync: false
      - key: VITE_BACKEND_URL
        sync: false
